title: Databases
description: To track updates to Teaching Databases
template:
  repo: databases-template
  name: databases
  description: Teaching Databases
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
